In [29]:
import qutip as qt
import numpy as np

I = qt.qeye(2)
X = qt.sigmax()
Y = qt.sigmay()
Z = qt.sigmaz()

In [185]:
#U1 = 1 / np.sqrt(2) * np.matrix(np.array([[1, 1, 0, 0],[1, -1, 0, 0],[0, 0, 1, 0],[0, 0, 0, 1]]))
#U2 = 1 / np.sqrt(2) * np.matrix(np.array([[0, 0, 1, -1],[0, 0, 1, 1],[1, 1, 0, 0],[-1, 1, 0, 0]]))
#U3 = 1/np.sqrt(2)* np.block([[I, I],[-X, X]])
U4 =  1/np.sqrt(2)*np.block([[I, Y],[I,-Y]])
U = qt.Qobj(U4, dims=[[2, 2], [2, 2]])
(U * U.dag())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [193]:
H2 = qt.tensor(qt.qeye(2), qt.sigmaz()) #+ qt.tensor(qt.sigmax(), qt.qeye(2))
H1 = qt.tensor(qt.sigmay(), qt.qeye(2)) #+ qt.tensor(qt.qeye(2), qt.sigmax())

In [194]:
display(U * H1 * U.dag())
display(U * H2 * U.dag())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0.  1.]
 [ 0.  0. -1.  0.]
 [ 0. -1.  0.  0.]
 [ 1.  0.  0.  0.]]

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]
 [ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]]